[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Enables Single Page App (SPA) routing (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
