export const teamMembers = [
  {
    name: "Oladotun Ajayi",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Oladotun-Ajayi.avif",
    role: "Lead LLN",
    description: "It is possible to do great things from a small place",
  },
  {
    name: "Emmanuel Nduka",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Emmanuel-Nduka.avif",
    role: "Co-Lead LLN",
    description: "No man can do these things except God be with him",
  },
  {
    name: "Tomide Williams",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Tomide-Williams.avif",
    role: "Team Management Lead",
    description: "If it's got to be, it's up to me",
  },
  {
    name: "Chioma Arah",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Chioma-Arah.avif",
    role: "Head, PR & Event Marketing",
    description: "Do the best you can until you know better",
  },
  {
    name: "Goshen Mmoneke",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Goshen-Mmoneke.avif",
    role: "Head, Awards Management",
    description: "There is nothing small about Goshen",
  },
  {
    name: "Tosin Olomu",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Tosin-Olomu.avif",
    role: "Head, Media",
    description: "You can do it",
  },
  {
    name: "Alabi Joshua",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Alabi-Joshua.avif",
    role: "Head, Logistics",
    description: "Can't find your quote sir....",
  },
  {
    name: "Bernice Orji",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Bernice-Orji.avif",
    role: "Head, Community",
    description: "God is with her, she cannot fail",
  },
  {
    name: "Clinton Okhai",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Clinton-Okhai.avif",
    role: "Head, Ticketing",
    description: "Growth is your ultimate purpose; your destiny is to multiply",
  },
  {
    name: "Ebenezer Ogunbode",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Ebenezer-Ogunbode.avif",
    role: "Head, Event Management",
    description: "Don't do it afraid, do it by faith",
  },
  {
    name: "Faizat Hussein",
    LinkedInURL: "https://linkedin.com/in/tangafoaf",
    teamImg: "/Faizat-Hussein.avif",
    role: "Head, Content & Social Media",
    description: "Dare to advance",
  },
  {
    name: "Isreal Aluko",
    LinkedInURL: "https://linkedin.com/in/eazyisreal",
    teamImg: "/Isreal-Aluko.avif",
    role: "Head, Web Development",
    description: "Do it afraid",
    },
  //Add more team members here as needed
];
