export const teamMembers = [
  {
    name: "Oladotun Ajayi",
    LinkedInURL: "https://www.linkedin.com/in/oladotun-ajayi-precious",
    twitterURL: "",
    websiteURL: "https://www.instagram.com/_oladotunajayi?igsh=MXNpbjh2Y2JxdnQ4bw==",
    teamImg: "/Oladotun-Ajayi.avif",
    role: "Lead LLN",
    description: "It is possible to do great things from a small place",
  },
  {
    name: "Emmanuel Nduka",
    LinkedInURL: "https://www.linkedin.com/in/emmanuel-nduka",
    twitterURL: "",
    websiteURL: "https://www.instagram.com/emmanuel_ndukka?igsh=MXVxYzd4MWd0bHR1cA==",
    teamImg: "/Emmanuel-Nduka.avif",
    role: "Co-Lead LLN",
    description: "No man can do these things except God be with him",
  },
  {
    name: "Tomide Williams",
    LinkedInURL: "https://ng.linkedin.com/in/tomidewill",
    twitterURL: "https://x.com/value_preneur?lang=en",
    websiteURL: "https://www.instagram.com/tomide_williams/",
    teamImg: "/Tomide-Williams.avif",
    role: "Team Management Lead",
    description: "If it's got to be, it's up to me",
  },
  {
    name: "Christiana Kuku ",
    LinkedInURL: "https://www.linkedin.com/in/christiana-kuku-9b1544232",
    twitterURL: "https://x.com/Kuku_Christiana?t=rIft-uwJ6VADClO5fuvgQQ&s=09",
    websiteURL: "https://linktr.ee/christianakuku",
    teamImg: "/Christiana-Kuku.avif",
    role: "Head, PR & Event Marketing",
    description: `Your story didn’t break you. It branded you. Now build with it.`,
  },
  {
    name: "Goshen Mmoneke",
    LinkedInURL: "https://www.linkedin.com/in/mmonekegoshen",
    twitterURL: "https://x.com/mmonekegoshen?s=21",
    websiteURL: "",
    teamImg: "/Goshen-Mmoneke.avif",
    role: "Head, Awards Management",
    description: "There is nothing small about Goshen",
  },
  {
    name: "Tosin Olomu",
    LinkedInURL: "http://www.linkedin.com/in/tosinolomu",
    twitterURL: "http://www.x.com/mrtosinolomu",
    websiteURL: "http://www.instagram.com/mrtosinolomu_",
    teamImg: "/Tosin-Olomu.avif",
    role: "Head, Media",
    description: "You can do it",
  },
  {
    name: "Alabi Joshua",
    LinkedInURL: "https://bit.ly/3ErmHdS",
    twitterURL: "https://bit.ly/3Gq8L4c",
    websiteURL: "",
    teamImg: "/Alabi-Joshua.avif",
    role: "Head, Logistics",
    description: "Fortis Fortuna Adiuvat",
  },
  {
    name: "Bernice Orji",
    LinkedInURL: "https://www.linkedin.com/in/bernice-orji",
    twitterURL: "https://instagram.com/officialberniceorji",
    websiteURL: "https://linktr.ee/berniceo",
    teamImg: "/Bernice-Orji.avif",
    role: "Head, Community",
    description: "God is with her, she cannot fail",
  },
  {
    name: "Clinton Okhai",
    LinkedInURL: "https://www.linkedin.com/in/clinton-okhai?",
    twitterURL: "https://x.com/Clintonokhai01",
    websiteURL: "https://www.instagram.com/theclintonokhai",
    teamImg: "/Clinton-Okhai.avif",
    role: "Head, Ticketing",
    description: "Growth is your ultimate purpose; your destiny is to multiply",
  },
  {
    name: "Ebenezer Ogunbode",
    LinkedInURL: "https://www.linkedin.com/in/ebenezer-ogunbode",
    twitterURL: "https://x.com/theonlyapex1",
    websiteURL: "https://www.instagram.com/ebenayomide?",
    teamImg: "/Ebenezer-Ogunbode.avif",
    role: "Head, Event Management",
    description: "Don't do it afraid, do it by faith",
  },
  {
    name: "Faizat Hussein",
    LinkedInURL: "https://www.linkedin.com/in/faizathussein/",
    twitterURL: "",
    websiteURL: "https://linktr.ee/faizathussein",
    teamImg: "/Faizat-Hussein.avif",
    role: "Head, Content & Social Media",
    description: "Dare to advance",
  },
  {
    name: "Isreal Aluko",
    LinkedInURL: "https://linkedin.com/in/eazyisreal",
    twitterURL: "https://x.com/eazyisreal_dev",
    websiteURL: "https://eazyisreal.netlify.app",
    teamImg: "/Isreal-Aluko.avif",
    role: "Head, Web Development",
    description: "Do it afraid",
  },
  {
    name: "Modupe Oreye",
    LinkedInURL: "https://www.linkedin.com/in/modupe-oreye",
    twitterURL: "https://x.com/modupe_oreye?t=ylHLjvWdC2olhd4tgfeEFQ&s=09",
    websiteURL: "https://www.instagram.com/the.modupe.oreye",
    teamImg: "/Modupe-Oreye.avif",
    role: " Quality Assurance Office",
    description: "Your playing Small won't serve you.",
  },
  {
    name: "Gabriel Ikenna",
    LinkedInURL: "https://www.linkedin.com/in/ikenna-gabriel",
    twitterURL: "https://x.com/Ikenna_Gabriel1",
    websiteURL: "https://www.instagram.com/ikennajustingabriel",
    teamImg: "/Gabriel-Ikenna.avif",
    role: "Head, Brand Design",
    description: "I can do all things through christ who strengthes me",
  },
  {
    name: "Tijesunimi Okunola",
    LinkedInURL: "https://www.linkedin.com/in/tijesunimi-abike-o",
    twitterURL: "",
    websiteURL: "https://www.instagram.com/okunolatijesunimi_abike",
    teamImg: "/Tijesunimi-Okunola.avif",
    role: "Head, Delegates & Attendes",
    description: "With God, Nothing is Impossible",
  },
  {
    name: "Mayowa Kolawole",
    LinkedInURL: "http://www.linkedin.com/in/oluwamayowa-kolawole",
    twitterURL: "",
    websiteURL: "https://www.instagram.com/oluwamayo_wa",
    teamImg: "/Mayowa-Kolawole.avif",
    role: "Head, Sponsorships and Partnerships",
    description: `"What you do makes a difference, and you have to decide what kind of difference you want to make." – Jane Goodall`,
  },
  //Add more team members here as needed
];
